import thumbnail1 from '../assets/images/thumbnail/usuk.jpg'
import thumbnail2 from '../assets/images/thumbnail/tktk.png'
import thumbnail3 from '../assets/images/thumbnail/region_jp_large.jpg'
import thumbnail4 from '../assets/images/thumbnail/sing.jpg'

export const Album = [
	{
		id: '1',
		album: 'US UK Playlist',
		artists: ['Trivo'],
		thumbnail: thumbnail1,
		playList: [
			{
				id: '1',
				title: 'One_Last_Time',
				artists: 'Ariana_Grande',
				albumId: 1,
				src: 'https://res.cloudinary.com/dsfwvhgtl/video/upload/v1653880277/mp3/Ariana_Grande_-_One_Last_Time_Lyric_Video_kxbwcm.mp3',
			},
			{
				id: '2',
				title: 'Ghost',
				artists: 'Justin_Bieber',
				albumId: 1,
				src: 'https://res.cloudinary.com/dsfwvhgtl/video/upload/v1653880283/mp3/Justin_Bieber_-_Ghost_vijkjf.mp3',
			},
			{
				id: '3',
				title: 'Señorita',
				artists: '_Shawn_Mendes',
				albumId: 1,
				src: 'https://res.cloudinary.com/dsfwvhgtl/video/upload/v1653880283/mp3/Se%C3%B1orita_-_Shawn_Mendes_Lyrics_mznvul.mp3',
			},
			{
				id: '4',
				title: 'Old_Town_Road',
				artists: 'Lil_Nas_X',
				albumId: 1,
				src: 'https://res.cloudinary.com/dsfwvhgtl/video/upload/v1653880298/mp3/Lil_Nas_X_-_Old_Town_Road_Lyrics_ft._Billy_Ray_Cyrus_wcepp2.mp3',
			},
			{
				id: '5',
				title: 'Everything_But_You_Lyrics',
				artists: 'Clean_Bandit',
				albumId: 1,
				src: 'https://res.cloudinary.com/dsfwvhgtl/video/upload/v1653896000/mp3/Clean_Bandit_-_Everything_But_You_Lyrics_ft._A7S_hfgwko.mp3',
			},
			{
				id: '6',
				title: 'Double_take',
				artists: 'Dhruv',
				albumId: 1,
				src: 'https://res.cloudinary.com/dsfwvhgtl/video/upload/v1653896017/mp3/dhruv_-_double_take_lyrics_tt489h.mp3',
			},
			{
				id: '7',
				title: 'Live_A_Lie',
				artists: 'Rival_x_Egzod',
				albumId: 1,
				src: 'https://res.cloudinary.com/dsfwvhgtl/video/upload/v1653896015/mp3/Rival_x_Egzod_-_Live_A_Lie_ft._Andreas_Stone_NCS_Release_gtzxni.mp3',
			},
		],
	},
	{
		id: '2',
		album: 'TikTok Remix',
		artists: ['Trivo'],
		thumbnail: thumbnail2,
		playList: [
			{
				id: '1',
				title: 'End_Like_This',
				artists: 'Steve_Aoki',
				albumId: 2,
				src: 'https://res.cloudinary.com/dsfwvhgtl/video/upload/v1653896018/mp3/Steve_Aoki_Yellow_Claw_-_End_Like_This_ft._RUNN_Arknights_Soundtrack_Music_Video_vn8wsz.mp3',
			},
			{
				id: '2',
				title: 'I_m_Blue_Remix',
				artists: 'No name',
				albumId: 2,
				src: 'https://res.cloudinary.com/dsfwvhgtl/video/upload/v1653896014/mp3/I_m_Blue_Remix_Tiktok_2021_-_%E5%8D%81%E5%85%AB%E9%97%B2%E5%AE%A2_%E7%AC%91%E5%8C%A0_-_XUFEIH___Nh%E1%BA%A1c_N%E1%BB%81n_Hot_TikTok___%E6%8A%96%E9%9F%B3_DouYin___L%E1%BB%A3i_Music_yvlla8.mp3',
			},
			{
				id: '3',
				title: 'Statement',
				artists: 'NEFFEX',
				albumId: 2,
				src: 'https://res.cloudinary.com/dsfwvhgtl/video/upload/v1653896010/mp3/NEFFEX_-_Statement_Copyright_Free_rze8t0.mp3',
			},
			{
				id: '4',
				title: 'Breathe',
				artists: 'Mackenzie_Ziegler',
				albumId: 2,
				src: 'https://res.cloudinary.com/dsfwvhgtl/video/upload/v1653896007/mp3/Breathe_-_Mackenzie_Ziegler_Lyrics_Vietsub_cpnnpn.mp3',
			},
			{
				id: '5',
				title: 'Industry_Baby_E.T',
				artists: 'Lil_Nas_X_Katy_Perry',
				albumId: 2,
				src: 'https://res.cloudinary.com/dsfwvhgtl/video/upload/v1653880287/mp3/Arcane_VI_-_Industry_Baby_E.T._Edit_Lil_Nas_X_Katy_Perry_loffeo.mp3',
			},
		],
	},
	{
		id: '3',
		album: 'JPOP MUSIC',
		artists: ['Trivo'],
		thumbnail: thumbnail3,
		playList: [
			{
				id: '1',
				title: 'HD_Fate_stay_night_Heaven_s_Feel_III.Spring_Song_-_Aimer_-_春はゆく_中日字幕_pmxubs',
				artists: 'Aimer',
				albumId: 3,
				src: 'https://res.cloudinary.com/dsfwvhgtl/video/upload/v1653896022/mp3/HD_Fate_stay_night_Heaven_s_Feel_III.Spring_Song_-_Aimer_-_%E6%98%A5%E3%81%AF%E3%82%86%E3%81%8F_%E4%B8%AD%E6%97%A5%E5%AD%97%E5%B9%95_pmxubs.mp3',
			},
			{
				id: '2',
				title: 'HD_Fate_Grand_Order_-_絕對魔獸戰線巴比倫尼亞_-_ED3_-_milet_-_Tell_me_中日字幕_md4qsx',
				artists: 'Milet',
				albumId: 3,
				src: 'https://res.cloudinary.com/dsfwvhgtl/video/upload/v1653896003/mp3/HD_Fate_Grand_Order_-_%E7%B5%95%E5%B0%8D%E9%AD%94%E7%8D%B8%E6%88%B0%E7%B7%9A%E5%B7%B4%E6%AF%94%E5%80%AB%E5%B0%BC%E4%BA%9E_-_ED3_-_milet_-_Tell_me_%E4%B8%AD%E6%97%A5%E5%AD%97%E5%B9%95_md4qsx.mp3',
			},
			{
				id: '3',
				title: 'YOASOBI「群青」Official Music Video',
				artists: 'YOASOBI',
				albumId: 3,
				src: 'https://res.cloudinary.com/dsfwvhgtl/video/upload/v1653896004/mp3/YOASOBI.mp3',
			},
		],
	},
	{
		id: '4',
		album: '"The Sing" Songtrack',
		artists: ['Trivo'],
		thumbnail: thumbnail4,
		playList: [
			{
				id: '1',
				title: 'A_Sky_Full_of_Stars',
				artists: 'Sing 2',
				albumId: 4,
				src: 'https://res.cloudinary.com/dsfwvhgtl/video/upload/v1653896002/mp3/Sing_2___A_Sky_Full_of_Stars_Song___Sing_2_uvuvzd.mp3',
			},
			{
				id: '2',
				title: 'A_Real_Rock_Star',
				artists: 'Sing 2',
				albumId: 4,
				src: 'https://res.cloudinary.com/dsfwvhgtl/video/upload/v1653895992/mp3/Sing_-_A_Real_Rock_Star_Scene___Fandango_Family_xohg5b.mp3',
			},
			{
				id: '3',
				title: 'Could_Have_Been_Me_Song',
				artists: 'Sing 2',
				albumId: 4,
				src: 'https://res.cloudinary.com/dsfwvhgtl/video/upload/v1653895992/mp3/Sing_2___Could_Have_Been_Me_Song___Sing_2_ewyfov.mp3',
			},
			{
				id: '4',
				title: 'Break_Free_Song',
				artists: 'Sing 2',
				albumId: 4,
				src: 'https://res.cloudinary.com/dsfwvhgtl/video/upload/v1653895991/mp3/Sing_2___Break_Free_Song___Sing_2_dyo9pc.mp3',
			},
			{
				id: '5',
				title: 'There_s_Nothing_Holdin_Me_Back',
				artists: 'Sing 2',
				albumId: 4,
				src: 'https://res.cloudinary.com/dsfwvhgtl/video/upload/v1653895989/mp3/Sing_2___There_s_Nothing_Holdin_Me_Back_Song___Sing_2_uvqtt6.mp3',
			},
			{
				id: '6',
				title: 'I_Like_It_Song',
				artists: 'Sing 2',
				albumId: 4,
				src: 'https://res.cloudinary.com/dsfwvhgtl/video/upload/v1653895989/mp3/Sing_2___I_Like_It_Song_Cardi_B_Lyrics___Sing_2_zemshm.mp3',
			},
			{
				id: '7',
				title: 'I_m_Still_Standing_Taron_Egerton',
				artists: 'Sing 2',
				albumId: 4,
				src: 'https://res.cloudinary.com/dsfwvhgtl/video/upload/v1653896010/mp3/SING_Song_I_m_Still_Standing_Taron_Egerton_as_Johnny_HD_kkmfqk.mp3',
			},
		],
	},
]
